### ISSUE TITLE
Sort Exception

### ISSUE THREAD

**Issue by BenKoth** [JanKallman/EPPlus#345]
I encountered a bug trying to sort. It seems to be related to the number of rows, but I'm not positive. I've attached a sample spreadsheet and here is sample code to reproduce the bug.
[test.xlsx](https://github.com/JanKallman/EPPlus/files/2578489/test.xlsx)

```
using (ExcelPackage package = new ExcelPackage(new FileInfo(@"C:\temp\test.xlsx")))
{
	var worksheet = package.Workbook.Worksheets["test"];
	int[] sortColumns = new int[1];
	sortColumns[0] = 0;	
	worksheet.Cells["A2:A30864"].Sort(sortColumns);
}
```

This produces the following exception:
ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.

I was only able to track it down to CellStore.cs, DeletePage method. I didn't dig deep enough into the _pages arrays to understand why there weren't enough pages to copy.

Thanks
Ben

**Comment by JanKallman** [comment]
Fixed in latest commit

**Comment by BenKoth** [comment]
Thanks! Do you know when the next NuGet package will be available with this fix? Trying to decide if I can just wait for that or if I should compile my own copy.

**Comment by WTSParadigm** [comment]
It looks like this is still an issue. I've encountered it again, here's a sample spreadsheet that's a bit bigger. Basically the same test code, just a larger range to sort:
  using (ExcelPackage package = new ExcelPackage(new FileInfo(@"C:\temp\issue345.xlsx")))
                {
                    var worksheet = package.Workbook.Worksheets["test"];
                    int[] sortColumns = new int[1];
                    sortColumns[0] = 0;
                    worksheet.Cells["A2:A64515"].Sort(sortColumns);
                }

[issue345.xlsx](https://github.com/JanKallman/EPPlus/files/3238322/issue345.xlsx)
